apiVersion: v1
kind: Service
metadata:
  name: grredis
  labels:
    app: redis-server
spec:
  type: NodePort
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
      nodePort: 31119
  selector:
    app: redis-server
---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: grredis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
      - name: grredis
        image: cragginstylie/grredis:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          protocol: TCP
